// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCemnKQAXPkuZo0HqJplUtLLRm7vObw9q4',
    appId: '1:635137896413:web:fa3cbdc61369adfad69034',
    messagingSenderId: '635137896413',
    projectId: 'flutter-chat-app-2c016',
    authDomain: 'flutter-chat-app-2c016.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2c016.firebasestorage.app',
    measurementId: 'G-3QCZ7YK7EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBll9a1ZM4OKDMOMOVRtVN9lPEq9g4fKnE',
    appId: '1:635137896413:android:d96ef27d98c7adbad69034',
    messagingSenderId: '635137896413',
    projectId: 'flutter-chat-app-2c016',
    storageBucket: 'flutter-chat-app-2c016.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCemnKQAXPkuZo0HqJplUtLLRm7vObw9q4',
    appId: '1:635137896413:web:0f28b78425154d29d69034',
    messagingSenderId: '635137896413',
    projectId: 'flutter-chat-app-2c016',
    authDomain: 'flutter-chat-app-2c016.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2c016.firebasestorage.app',
    measurementId: 'G-K9FFQWWNWW',
  );
}
